services:
  - type: web
    name: laaabubu-vehicle-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --threads 4 --timeout 120 --bind 0.0.0.0:$PORT vv:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
